# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'index.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_index_goruntu(object):
    def setupUi(self, index_goruntu):
        index_goruntu.setObjectName("index_goruntu")
        index_goruntu.resize(599, 486)
        self.centralwidget = QtWidgets.QWidget(index_goruntu)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(150, 150, 301, 201))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnSearch = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnSearch.setObjectName("btnSearch")
        self.verticalLayout.addWidget(self.btnSearch)
        self.btnentry = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnentry.setObjectName("btnentry")
        self.verticalLayout.addWidget(self.btnentry)
        self.btndelete = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btndelete.setObjectName("btndelete")
        self.verticalLayout.addWidget(self.btndelete)
        self.btnupdate = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnupdate.setObjectName("btnupdate")
        self.verticalLayout.addWidget(self.btnupdate)
        self.lbltitle = QtWidgets.QLabel(self.centralwidget)
        self.lbltitle.setGeometry(QtCore.QRect(160, 50, 291, 91))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbltitle.setFont(font)
        self.lbltitle.setObjectName("lbltitle")
        index_goruntu.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(index_goruntu)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 599, 21))
        self.menubar.setObjectName("menubar")
        index_goruntu.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(index_goruntu)
        self.statusbar.setObjectName("statusbar")
        index_goruntu.setStatusBar(self.statusbar)

        self.retranslateUi(index_goruntu)
        QtCore.QMetaObject.connectSlotsByName(index_goruntu)

    def retranslateUi(self, index_goruntu):
        _translate = QtCore.QCoreApplication.translate
        index_goruntu.setWindowTitle(_translate("index_goruntu", "MainWindow"))
        self.btnSearch.setText(_translate("index_goruntu", "Kayıt Arama"))
        self.btnentry.setText(_translate("index_goruntu", "Kayıt Ekle"))
        self.btndelete.setText(_translate("index_goruntu", "Kayıt Silme"))
        self.btnupdate.setText(_translate("index_goruntu", "Kayıt Güncelleme"))
        self.lbltitle.setText(_translate("index_goruntu", "        Neşeli Toynaklar Kliniği"))
